twig:
    default_path: '%kernel.project_dir%/templates'
    
    # pour la costomisation des FORM
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
